### ISSUE TITLE
[Feature] Shortcut keys for Pausing, Seeking Forward and Backward, and Volume 

### ISSUE THREAD

**Issue by MrBouBou** [yukino-app/yukino#110]
**Is your feature request related to a problem? Please describe.**
I'm really impressed with the player implemented in this app; it's fast, smooth, and doesn't buffer. But what I really like the most is the option to choose the duration you like when seeking which almost every other players lack or have 5s as minimum. However, it's kind of bothersome to move the mouse every single time for the seeking bar to appear and either click the pause button or seeking button.

**Describe the solution you'd like**
It would be really convenient if you guys could add space bar for pausing and left key and right key for seeking backward and forward. Oh...and up and down for volume of course. 

Also, I would really like you guys to respond whether it's possible to add or not so that I know if I can keep my hopes up or not.

**Comment by zyrouge** [comment]
Has been done as of v1.0.14-beta.0.
