### ISSUE TITLE
[Bug] Video Quality doesn't load for a source in gogoanime

### ISSUE THREAD

**Issue by rsmyst** [yukino-app/yukino#155]
I just tried out the app. while playing a video, realized that one of the sources in gogoanime doesn't show the video. it just shows as unknown. 2 sources are available though, but the second one where the video quality shows up doesn't work. video doesn't load at all. here's a screen shot.
![image](https://user-images.githubusercontent.com/30620767/139571172-7cc7647c-b168-478d-8e0b-b81cf8926174.png)

**Comment by zyrouge** [comment]
Sbplay could sometimes be slow. The website doesn't provide the quality so it cannot be determined. Not every source is available due to technical limitations like missing virtual DOMs, obfuscations and captchas. Closing this as it's not an issue.
