### ISSUE TITLE
[Bug - Extension] Gogoanime.be doesn't work

### ISSUE THREAD

**Issue by zeankundev** [yukino-app/yukino#160]
**Describe the bug**
The bug was when I select Gogoanime.be in the Yukino search bar, it appeared as "No results were found" but when I looked up on gogoanime.be (the real website) searched perfectly and the query in the website was in.

**To Reproduce**

1. Go to 'search'
2. Click on 'the search box' and select Gogoanime.be
3. Type the query

**Expected behavior**
Yukino cannot find the query based on Gogoanime.be but on the website itself was found

**Screenshots**
![image](https://user-images.githubusercontent.com/58360911/141403328-c2b098d4-998c-47fb-b0a5-659f5cb3185f.png)
![image](https://user-images.githubusercontent.com/58360911/141403347-565e6ec1-50cd-4801-b171-a711a6c61d05.png)

**Environment (please complete the following information):**

-   OS: Windows 10 Pro
-   Version: v1.0.7-beta.0

 ## Checklist
 -   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
This has been known for a week and was announced in the discord server. Currently virtual DOMs are being implemented which could fix this issue.

**Comment by zyrouge** [comment]
Has been fixed as of v1.0.9-beta.0.
