### ISSUE TITLE
Thumbnail, Episode title, description.

### ISSUE THREAD

**Issue by Bungeexgum** [yukino-app/yukino#163]
Will it be possible to add these features? Anyway the player is messy those buttons are too big they are blocking the subtitles can you make it a bit smaller, or is ther an option to off them. And there's no genre of anime only synopsis

**Comment by zyrouge** [comment]
> Anyway the player is messy those buttons are too big they are blocking the subtitles can you make it a bit smaller, or is ther an option to off them.

The overlay is hidden/will be hidden after some time or by tapping on screen, thus it's an invalid point to say those are too big and they "hide" the subtitle.

Also I'm making this as invalid as it violates the Contribution Guidelines. If you want to request something please do some research and ask a single feature per issue. Not being rude but it's annoying to deal with pointless issues and the fact the title doesn't match the description.
