### ISSUE TITLE
[Bug] Kawaiifu not working?

### ISSUE THREAD

**Issue by OukilIl** [yukino-app/yukino#166]
**Describe the bug**
Kawaiifu leads to just waiting eternally

**To Reproduce**
search any anime with kawaiifu and select one

**Environmen**

-   OS: manjaro
-   latest version

**Additional context**
it's probably because of cloudflare

 
 ## Checklist
 -   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
Just tested it and seems to be true. It seems to require extra workarounds, I'll make sure to do those in the next update.

**Comment by zyrouge** [comment]
Ah tried enough and noticed that cloudflare was presenting a hCaptcha to solve which is not bypassable with current setup. I'll have to give up until they turn off the under attack mode. Feel free to open if you have a workaround or just wanted to say something.
