### ISSUE TITLE
The app is not even opening 

### ISSUE THREAD

**Issue by Ink25** [yukino-app/yukino#170]
The app is not even opening. When I open it, it freezes.

**To Reproduce**

1. Click on the app.
2. It freezes. 

**Recording**

https://user-images.githubusercontent.com/85929295/147686771-dd9929d3-e4ba-4564-8925-d9c02fe54737.mp4

**Environment :**

-   Android 5.1
-   App version v1.0.10-beta.0

<details>
  <summary>Logs</summary>
  
  
  
</details>
 
 ## Checklist
 -   [ ☑ ] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
Seems like it failed preliminary requirements. I cannot help without the logs unfortunately. Is your phone rooted?

**Comment by Ink25** [comment]
> Seems like it failed preliminary requirements. I cannot help without the logs unfortunately. Is your phone rooted?

No. I don't think it is.

**Comment by Ink25** [comment]
Oh, thanks
