### ISSUE TITLE
Database (ObjectBox) fails to initialize

### ISSUE THREAD

**Issue by Ink25** [yukino-app/yukino#171]
This Was The error. 

![Screenshot_20211231_115128](https://user-images.githubusercontent.com/85929295/147807129-a4632a8a-d4ac-446b-b7c0-50b26ff330a4.png)

This Was The error code:

Message: Something horribly went wrong.
Error: Null check operator used on a null value
Stack trace:
#0      AppState.settings (package:yukino_app/modules/app/state.dart:26)
#1      AppLifecycle.preinitialize (package:yukino_app/modules/app/lifecycle.dart:118)
<asynchronous suspension>
#2      main (package:yukino_app/main.dart:10)
<asynchronous suspension>

**Comment by zyrouge** [comment]
Closing #170 in favour of this.

**Comment by Ink25** [comment]
> Closing #170 in favour of this.

Ok

**Comment by Ink25** [comment]
Another error. 
![Screenshot_20211231_141110](https://user-images.githubusercontent.com/85929295/147812953-f29a5396-5688-42b8-b0f9-a14ab5da32e9.png)

Error code:

Message: Something horribly went wrong.
Error: Invalid argument(s): Failed to load dynamic library 'libobjectbox-jni.so': dlopen failed: library "libobjectbox-jni.so" not found
Stack trace:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _tryObjectBoxLibFile (package:objectbox/src/native/bindings/bindings.dart:56)
#3      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:66)
#4      C (package:objectbox/src/native/bindings/bindings.dart:84)
#5      new Model (package:objectbox/src/native/model.dart)
#6      new Store (package:objectbox/src/native/store.dart:105)
#7      openStore (package:yukino_app/modules/database/objectbox/objectbox.g.dart:136)
#8      DatabaseManager.initialize (package:yukino_app/modules/database/database.dart:20)
<asynchronous suspension>
#9      AppLifecycle.preinitialize (package:yukino_app/modules/app/lifecycle.dart:76)
<asynchronous suspension>
#10     main (package:yukino_app/main.dart:10)
<asynchronous suspension>

**Comment by zyrouge** [comment]
Android version?

**Comment by Ink25** [comment]
> Android version? and fyi it's something related to [objectbox](https://github.com/objectbox/objectbox-dart).
Android version 5.0.2

**Comment by Ink25** [comment]
Android version 5.0.2

**Comment by zyrouge** [comment]
Seems like only Android 7+ is supported. Refer: https://github.com/objectbox/objectbox-dart/pull/328.
