### ISSUE TITLE
[Feature] Save Volume-Value and apply for the Media-Player

### ISSUE THREAD

**Issue by EhsanFox** [yukino-app/yukino#36]
**Is your feature request related to a problem? Please describe.**
for some people, they are a little sensitive about the audio volume, so they have to set it for every episode they watch

**Describe the solution you'd like**
whenever someone set the volume value to something, and when they skip to another ep/show the audio volume become the old one

**Describe alternatives you've considered**
it might be impossible because of HTML and stuff, so we still can have a settings menu to set our default audio to it

**Additional context**
none.

**Comment by zyrouge** [comment]
Delaying this until custom video player is made. :)
