### ISSUE TITLE
[Bug] Discord RPC Privacy Mode get's overwritten

### ISSUE THREAD

**Issue by nayutune** [yukino-app/yukino#96]
**Describe the bug**
When Discord RPC Privacy Mode is enabled, doing anything that will update it like going to a different tab will reveal the status of what the user is doing on discord

**To Reproduce**
1. Go to 'Settings' tab
2. Set 'Discord RPC' to 'Enabled'
3. Set 'Discord RPC (Privacy Mode)' to 'Enabled'
4. Look at your discord activity status (Activity is hidden)
5. Go to any other tab in Yukino
6. Look at your discord activity status (Activity got revealed)

**Expected behavior**
Activity should be not revealed for as long as the option remains enabled regardless of what's being opened

**Screenshots**
![Preview](https://user-images.githubusercontent.com/74027819/129208142-494e2627-568f-438c-a02e-8dcb6cd3cb51.png)

 - OS: Windows 10
 - Yukino Version: 0.0.31-beta.0

**Additional context**
Restarting the app does not change described behavior

**Comment by zyrouge** [comment]
Fixed in v0.0.32-beta.0 🎉
